character_mapping:
  户山香澄:
  - 1
  花园多惠:
  - 2
  牛込里美:
  - 3
  山吹沙绫:
  - 4
  市谷有咲:
  - 5
  美竹兰:
  - 6
  青叶摩卡:
  - 7
  上原绯玛丽:
  - 8
  宇田川巴:
  - 9
  羽泽鸫:
  - 10
  弦卷心:
  - 11
  濑田薰:
  - 12
  北泽育美:
  - 13
  松原花音:
  - 14
  奥泽美咲:
  - 15
  丸山彩:
  - 16
  冰川日菜:
  - 17
  白鹭千圣:
  - 18
  大和麻弥:
  - 19
  若宫伊芙:
  - 20
  凑友希那:
  - 21
  冰川纱夜:
  - 22
  今井莉莎:
  - 23
  宇田川亚子:
  - 24
  白金燐子:
  - 25
  仓田真白:
  - 26
  桐谷透子:
  - 27
  广町七深:
  - 28
  二叶筑紫:
  - 29
  八潮瑠唯:
  - 30
  LAYER:
  - 31
  LOCK:
  - 32
  MASKING:
  - 33
  PAREO:
  - 34
  CHU²:
  - 35
  高松灯:
  - 36
  千早爱音:
  - 37
  要乐奈:
  - 38
  长崎素世:
  - 39
  椎名立希:
  - 40
  丰川祥子:
  - 1
  若叶睦:
  - 2
  三角初华:
  - 3
  八幡海铃:
  - 4
  祐天寺若麦:
  - 5
parsing:
  default_narrator_name: ' '
  max_short_speaker_name_length: 6
  max_speaker_name_length: 50
patterns:
  speaker_no_quotes: ^([\w\s]+)\s*[：:]\s*(.*?)$
  speaker_quoted: ^([\w\s]+)\s*[：:]\s*[""](.*?)[""]$
